### ISSUE TITLE
Please Support ARM64 for Apple Silicon Users

### ISSUE THREAD

**Issue by EmrecanKaracayir** [Sedeniono/VSDoxyHighlighter#4]
It can be easily done by following these [steps](https://devblogs.microsoft.com/visualstudio/now-introducing-arm64-support-for-vs-extensions/).

**Comment by Sedeniono** [comment]
@EmrecanKaracayir Well, the problem is I don't really have access to an ARM machine where I could test it. But I don't think there is anything in the code that is x64 specific. So, I [attached VSDoxyHighlighter.zip](https://github.com/user-attachments/files/15568185/VSDoxyHighlighter.zip), which is a vsix package where I simply added the ARM platform to the vsix manifest as supported platform. Could you please try it out (simply double click the file to install)? Specifically, please check:
* Obviously syntax highlighting
* Autocomplete (IntelliSense)
* Autocomplete of the argument of `\param`
* Quick info

If you report that all 4 things work, I will merge it into main and push it into the marketplace.
Thanks!

**Comment by EmrecanKaracayir** [comment]
Thank you for your effort. Let's make it real!

### Test Environment

![image](https://github.com/Sedeniono/VSDoxyHighlighter/assets/84916904/20c2e3de-76f5-4b79-8c47-136a04639e74)

### Test Results

- **Installing:** No problem,
  - **Proof:** ![image](https://github.com/Sedeniono/VSDoxyHighlighter/assets/84916904/36c65a67-72fc-4c77-85da-8ac46422c639)
- **Syntax highlighting:** No problem,
  - **Proof:**  ![image](https://github.com/Sedeniono/VSDoxyHighlighter/assets/84916904/0b26c7ac-27e3-4c88-bdc6-a7d8336cd0a7)
- **Autocomplete:** No problem,
  - **Proof:** ![image](https://github.com/Sedeniono/VSDoxyHighlighter/assets/84916904/91256390-7bca-4947-b13c-af1843d56d37)
- **Autocomplete (parameters):** No problem,
  - **Proof:** ![image](https://github.com/Sedeniono/VSDoxyHighlighter/assets/84916904/98f8c5ca-fba5-41ae-9fd2-8d9427340047)
- **Quick info:** No problem.
  - **Proof:** ![image](https://github.com/Sedeniono/VSDoxyHighlighter/assets/84916904/ebd83939-6b3f-4c46-a1a6-a0bc96181c36)

---

Everything looks ok!

**Comment by EmrecanKaracayir** [comment]
By the way quick info that is shown when hovered over documented symbols are also shown, no problem there either.

**Comment by Sedeniono** [comment]
@EmrecanKaracayir Thank a lot for testing! I just [released](https://github.com/Sedeniono/VSDoxyHighlighter/releases/tag/v1.7.0) a new version (1.7.0) and pushed it to the [marketplace](https://marketplace.visualstudio.com/items?itemName=Sedenion.VSDoxyHighlighter).
