### ISSUE TITLE
Support for Visual Studio Code

### ISSUE THREAD

**Issue by parmi93** [Sedeniono/VSDoxyHighlighter#5]
Is there any chance this extension will be made available for VS Code too?
Or do you know if there is something similar for VS Code?

**Comment by Sedeniono** [comment]
No, I do not plan to port it to VS Code, because it would require a complete rewrite since both use entirely different frameworks (I think?). Sorry.

VS code comes by default with some highlighting of doxygen commands. Or at least the cpp tools come with it. Compare https://github.com/microsoft/vscode-cpptools/issues/4089
